<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Tedd.RTree/Tedd.RTree.csproj" />
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="RBush" Version="4.0.0" />
    <PackageReference Include="NetTopologySuite" Version="2.6.0" />
    <PackageReference Include="RTree" Version="1.1.0" />
    <PackageReference Include="Enyim.Collections.RTree" Version="1.0.5" />
    <PackageReference Include="SharpTrees" Version="1.0.6" />
  </ItemGroup>
</Project>
